services:

  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    container_name: iris-api
    ports:
      - "8000:8000"

  streamlit:
    build:
      context: .
      dockerfile: Dockerfile.streamlit
    container_name: iris-streamlit
    ports:
      - "8501:8501"
    depends_on:
      - api

  prometheus:
    image: prom/prometheus:latest
    container_name: iris-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    depends_on:
      - api

  grafana:
    image: grafana/grafana
    container_name: iris-grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus