{
 "title": "Iris API AI",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 9, "x": 0, "y": 0 },
   "options": {
    "content": "# Monitoring de l'application IRIS_API_AI"
   }
  },
  {
   "title": "Etat de l'API",
   "type": "stat",
   "description": "Vérifie l'état de disponibilité de l'API",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "iris_api_up", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Requêtes API",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "iris_api_requests_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Erreurs API",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 6, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "iris_api_errors_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Latence moyenne",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\r\n  rate(iris_api_request_duration_seconds_sum[5m])\r\n  /\r\n  rate(iris_api_request_duration_seconds_count[5m])\r\n) * 1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Prédictions par classe",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 5, "x": 4, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (species) (\r\n  iris_predictions_total\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Taux de requêtes API",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 0, "y": 13 },
   "targets": [
    { "expr": "iris_api_requests_total", "legendFormat": "__auto" }
   ]
  }
 ]
}